import Footer from "@/components/footer/page";
import Navbar from "@/components/navbar/page";

import { Noto_Sans } from "next/font/google";
import "./globals.css";

const fonts = Noto_Sans({ weight: '400', subsets: ["latin"] });

export const metadata = {
  title: "Profile Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="autumn">
      <body className={fonts.className}>
        <div className="min-h-screen">
          <Navbar/>
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
